# Generated by Django 4.0.4 on 2023-09-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_rename_category_address_category_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='スポット名'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='スポット名'),
        ),
    ]
