# Generated by Django 4.0.4 on 2023-09-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_alter_address_description_alter_genre_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='category_genre',
            new_name='category',
        ),
    ]
