# Generated by Django 4.0.4 on 2023-09-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0005_rename_category_genre_genre_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='category_address',
            new_name='category',
        ),
    ]
