# Generated by Django 4.0.4 on 2023-09-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0006_rename_category_address_address_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='category',
            new_name='category_genre',
        ),
    ]
