# Generated by Django 4.0.4 on 2023-09-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0007_rename_category_genre_category_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='category',
            new_name='category_address',
        ),
    ]
