# Generated by Django 4.0.4 on 2023-09-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0008_rename_category_address_category_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.TextField(blank=True, null=True, verbose_name='スポット')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spot.addresscategory', verbose_name='エリア')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spot.genrecategory', verbose_name='ジャンル')),
            ],
        ),
        migrations.RemoveField(
            model_name='genre',
            name='category_genre',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
