# Generated by Django 4.0.4 on 2023-11-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_review_user_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ごはん', 'ごはん'), ('カフェ・パン・スイーツ・お菓子', 'カフェ・パン・スイーツ・お菓子'), ('イベント', 'イベント'), ('風景・景色', '風景・景色'), ('アート・カルチャー', 'アート・カルチャー'), ('お土産・お酒・雑貨', 'お土産・お酒・雑貨'), ('神社・寺院', '神社・寺院'), ('アクティビティ・体験・その他施設', 'アクティビティ・体験・その他施設')], max_length=100, null=True),
        ),
    ]
