# Generated by Django 4.0.4 on 2023-11-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='target',
            new_name='post',
        ),
    ]
