# Generated by Django 4.0.4 on 2023-11-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_created_at_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
