# Generated by Django 4.0.4 on 2023-11-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('ごはん', 'ごはん'), ('カフェ・パン・スイーツ・お菓子', 'カフェ・パン・スイーツ・お菓子'), ('イベント', 'イベント'), ('風景・景色', '風景・景色'), ('アート・カルチャー', 'アート・カルチャー'), ('お土産・お酒・雑貨', 'お土産・お酒・雑貨'), ('神社・寺院', '神社・寺院'), ('アクティビティ・体験・その他施設', 'アクティビティ・体験・その他施設')], max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='post.category'),
        ),
    ]
