# Generated by Django 4.0.4 on 2023-11-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_category_post_comment_remove_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
