# Generated by Django 4.0.4 on 2023-12-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wordcloud',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
