# Generated by Django 4.0.4 on 2024-01-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_foodcategory_post_cost_post_holiday_post_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='picture2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
