# Generated by Django 4.2.5 on 2023-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_map_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='comment',
            field=models.CharField(max_length=50, null=True, verbose_name='一言'),
        ),
    ]
