# Generated by Django 4.0.4 on 2023-10-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_map_comment'),
        ('map', '0004_map_number'),
    ]

    operations = [
    ]
