# Generated by Django 4.0.4 on 2023-10-28 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0006_likeformap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeForMap',
            new_name='Like',
        ),
    ]
