# Generated by Django 4.0.4 on 2023-11-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_rename_likeformap_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
