# Generated by Django 4.0.4 on 2023-12-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_post_options'),
        ('map', '0008_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='name2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
