# Generated by Django 4.0.4 on 2023-12-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_map_name2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='name2',
            new_name='post',
        ),
    ]
