# Generated by Django 4.0.4 on 2023-12-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('ごはん', 'ごはん'), ('カフェ・パン・スイーツ・お菓子', 'カフェ・パン・スイーツ・お菓子'), ('イベント', 'イベント'), ('風景・景色', '風景・景色'), ('アート・カルチャー', 'アート・カルチャー'), ('お土産・お酒・雑貨', 'お土産・お酒・雑貨'), ('神社・寺院', '神社・寺院'), ('アクティビティ・体験・その他施設', 'アクティビティ・体験・その他施設')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, null=True)),
                ('area_number', models.CharField(max_length=5, null=True)),
                ('name', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('wordcloud', models.ImageField(null=True, upload_to='')),
                ('category', models.ManyToManyField(related_name='categories', to='post2.category')),
            ],
            options={
                'ordering': ['-postlike2'],
            },
        ),
        migrations.CreateModel(
            name='PostLike2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post2.post2')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kutikomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('rate', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post2.post2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
