# Generated by Django 4.0.4 on 2023-12-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post2', '0002_rename_kutikomi_review2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post2',
            options={},
        ),
    ]
