# Generated by Django 4.0.4 on 2023-12-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_all', '0002_alter_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='area_number',
            field=models.CharField(max_length=5, null=True, verbose_name='番号'),
        ),
    ]
