# Generated by Django 4.0.4 on 2023-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_itinerary_time_alter_itinerary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
