# Generated by Django 4.0.4 on 2023-09-16 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_alter_itinerary_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='date',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='note',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='time',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_1',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_10',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_11',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_12',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_2',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_3',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_4',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_5',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_6',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_7',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_8',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='schedule_9',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
