# Generated by Django 4.0.4 on 2023-09-16 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_remove_itinerary_date_remove_itinerary_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='date_1',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='date_2',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='date_3',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_1',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_10',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_11',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_12',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_2',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_3',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_4',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_5',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_6',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_7',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_8',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='time_9',
            field=models.TimeField(auto_now=True),
        ),
    ]
