# Generated by Django 4.0.4 on 2023-09-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_itinerary_date_1_itinerary_date_2_itinerary_date_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='time_1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_10',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_11',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_12',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_2',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_3',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_4',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_5',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_6',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_7',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_8',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_9',
            field=models.TimeField(),
        ),
    ]
