# Generated by Django 4.0.4 on 2023-09-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0007_alter_itinerary_time_1_alter_itinerary_time_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='date_1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_1',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_11',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_12',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_9',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
