# Generated by Django 4.0.4 on 2023-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0011_alter_itinerary_time_10_alter_itinerary_time_11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_1',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
