# Generated by Django 4.0.4 on 2023-09-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0012_alter_itinerary_schedule_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
