# Generated by Django 4.0.4 on 2023-09-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0013_alter_itinerary_schedule_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='schedule_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
