# Generated by Django 4.0.4 on 2023-09-18 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0016_alter_itinerary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='time_1',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_10',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_11',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_12',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_2',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_3',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_4',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_5',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_6',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_7',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_8',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='time_9',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
