# Generated by Django 4.0.4 on 2023-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0021_alter_itinerary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='contributer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
