# Generated by Django 4.0.4 on 2023-11-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0022_itinerary_contributer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-id']},
        ),
    ]
