# Generated by Django 4.0.4 on 2023-12-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0025_alter_itinerary_category_alter_itinerary_companion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
