# Generated by Django 4.0.4 on 2023-12-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0027_remove_itinerary_picture_review_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='record',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
