# Generated by Django 4.0.4 on 2023-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0029_alter_itinerary_date_2_alter_itinerary_date_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
