# Generated by Django 4.0.4 on 2023-12-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0031_alter_itinerary_category_alter_itinerary_companion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
