# Generated by Django 4.0.4 on 2024-01-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0033_alter_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='age',
            field=models.CharField(blank=True, choices=[('10代', '10代'), ('20代', '20代'), ('30代', '30代'), ('40代', '40代'), ('50代', '50代'), ('60代', '60代'), ('70代', '70代'), ('80代以上', '10代以上')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='gender',
            field=models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性'), ('選択しない', '選択しない')], max_length=20, null=True),
        ),
    ]
