# Generated by Django 4.0.4 on 2024-01-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0034_itinerary_age_itinerary_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cost1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='cost2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='cost3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='cost4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
