# Generated by Django 4.0.4 on 2024-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0035_review_cost1_review_cost2_review_cost3_review_cost4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cost1',
            field=models.CharField(blank=True, choices=[('1000円未満', '1000円未満'), ('1000円〜2000円', '1000円〜2000円'), ('2000円〜3000円', '2000円〜3000円'), ('3000円〜4000円', '3000円〜4000円'), ('4000円〜5000円', '4000円〜5000円'), ('5000円〜6000円', '5000円〜6000円'), ('6000円以上', '6000円以上')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='cost2',
            field=models.CharField(blank=True, choices=[('5000円未満', '5000円未満'), ('5000円〜10000円', '5000円〜10000円'), ('10000円以上', '10000円以上')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='cost3',
            field=models.CharField(blank=True, choices=[('1000円未満', '1000円未満'), ('1000円〜2000円', '1000円〜2000円'), ('2000円〜3000円', '2000円〜3000円'), ('3000円〜4000円', '3000円〜4000円'), ('4000円〜5000円', '4000円〜5000円'), ('5000円〜6000円', '5000円〜6000円'), ('6000円以上', '6000円以上')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='cost4',
            field=models.CharField(blank=True, choices=[('1000円未満', '1000円未満'), ('1000円〜2000円', '1000円〜2000円'), ('2000円〜3000円', '2000円〜3000円'), ('3000円〜4000円', '3000円〜4000円'), ('4000円〜5000円', '4000円〜5000円'), ('5000円〜6000円', '5000円〜6000円'), ('6000円以上', '6000円以上')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='record',
            field=models.ImageField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=20, null=True, upload_to=''),
        ),
    ]
