# Generated by Django 4.0.4 on 2024-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0036_alter_review_cost1_alter_review_cost2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='record',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
